#!/usr/bin/env python3
"""Render changelog/index.html from changelog/releases.json.

releases.json is the source of truth, newest release first:

    [{"build": 17, "date": "2026-10-03", "headline": "...",
      "items": [{"kind": "new" | "improved" | "fixed", "text": "..."}]}]

The Divide app repo's scripts/release_notes.py appends to it on every
release and then runs this script. Standard library only.

Usage: scripts/build_changelog.py
"""

import datetime
import html
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "changelog" / "releases.json"
OUT = ROOT / "changelog" / "index.html"

KIND_LABELS = {"new": "New", "improved": "Improved", "fixed": "Fixed"}
KIND_ORDER = ["new", "improved", "fixed"]

PAGE = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="#ECEEE4">
  <title>Divide Changelog</title>
  <meta name="description" content="What's new in each release of Divide.">
  <link rel="icon" href="../icon.png">
  <link rel="apple-touch-icon" href="../apple-touch-icon.png">
  <link rel="alternate" type="application/json" href="releases.json" title="Divide releases">
  <link rel="stylesheet" href="../style.css">
</head>
<body>
<!-- Generated by scripts/build_changelog.py from releases.json. Don't edit by hand. -->
<header class="site-header">
  <a class="brand" href="../"><img src="../icon.png" alt="">Divide</a>
  <nav class="site-nav" aria-label="Site">
    <a href="../changelog/" aria-current="page">Changelog</a>
    <a href="../privacy/">Privacy</a>
    <a href="../support/">Support</a>
  </nav>
</header>

<main class="doc changelog">
  <h1>Changelog</h1>
  <p class="lede">What changed in each release of Divide for iPhone and iPad.</p>
{releases}
</main>

<footer class="site-footer">
  <p>Made in Vancouver by Kyle Marks.</p>
  <nav aria-label="Footer">
    <a href="../">Home</a>
    <a href="../privacy/">Privacy policy</a>
    <a href="../support/">Support</a>
  </nav>
</footer>
</body>
</html>
"""


def render_release(release):
    date = datetime.date.fromisoformat(release["date"])
    pretty_date = f"{date:%B} {date.day}, {date.year}"
    lines = [
        f'  <article class="release" id="build-{release["build"]}">',
        "    <header>",
        f'      <h2>{html.escape(release["headline"])}</h2>',
        f'      <p class="meta"><time datetime="{date.isoformat()}">{pretty_date}</time>'
        f' · <a href="#build-{release["build"]}">Build {release["build"]}</a></p>',
        "    </header>",
    ]
    for kind in KIND_ORDER:
        items = [item["text"] for item in release["items"] if item["kind"] == kind]
        if not items:
            continue
        lines.append(f'    <h3>{KIND_LABELS[kind]}</h3>')
        lines.append("    <ul>")
        lines.extend(f"      <li>{html.escape(text)}</li>" for text in items)
        lines.append("    </ul>")
    lines.append("  </article>")
    return "\n".join(lines)


def main():
    releases = json.loads(DATA.read_text())
    if releases:
        body = "\n".join(render_release(release) for release in releases)
    else:
        body = '  <p class="empty">The first release notes will appear here after the next release.</p>'
    OUT.write_text(PAGE.replace("{releases}", body))
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(releases)} releases)")


if __name__ == "__main__":
    main()
